#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi

if ! [[ -f /usr/bin/deborphan ]] || [[ $(dpkg --get-selections | grep -w "deborphan" | awk '{print $1}' | head -1) != deborphan ]]; then
	apt -q update
	apt -qy install deborphan
fi

rm -f /var/lib/dpkg/lock
rm -f /var/lib/apt/lists/lock
apt -q update
apt -y --allow-unauthenticated dist-upgrade
apt -y autoremove
apt autoclean
apt clean
apt -y purge $(deborphan --libdevel) $(deborphan --find-config) $(deborphan)
update-grub2
prelink -amR
history -c
rm -rf /tmp/*
rm -rf /var/tmp/*
echo -e "\e[00;1;92mFinalizado...\e[00m"
exit 0
