#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
apt update
apt -y --force-yes dist-upgrade
apt-get clean
apt-get -y autoremove
rm -rf /tmp/*
rm -rf /var/tmp/*
echo -e "\e[00;1;92mFinalizado...\e[00m"
exit 0
