#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
IFS=" "
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
	exit 1
fi

ipv6="/etc/sysctl.d/60-disableipv6.conf"
sysf="/etc/sysfs.conf"
quien=$(who | cut -d' ' -f1 | sort | uniq)
mkdir -p /etc/sysctl.d
add-apt-repository -y ppa:libreoffice/libreoffice-6-0
add-apt-repository -y ppa:sinfallas/stuff
add-apt-repository -y ppa:damentz/liquorix
add-apt-repository -y ppa:linuxenko/chkservice
echo "deb http://build.openvpn.net/debian/openvpn/release/2.4 xenial main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
wget -q https://swupdate.openvpn.net/repos/repo-public.gpg -O- | apt-key add -
apt -y purge zeitgeist rhythmbox-plugin-zeitgeist zeitgeist-core zeitgeist-datahub apt-xapian-index
apt -q update
apt -y install pssh chkservice mygit mykvm testdisk linux-image-liquorix-amd64 linux-headers-liquorix-amd64 vlc isomaster htop iotop intel-microcode ubuntu-restricted-extras prelink xterm pv localepurge tmux yad rar seahorse linux-firmware hwdata synaptic iftop fish pcmanfm gparted gnupg gpgv bleachbit gftp grsync libdvdread4 powertop libreoffice-l10n-es myspell-es ispanish brasero dconf-editor cups-pdf deborphan fslint compizconfig-settings-manager sysfsutils ssh uget yad gimp ocsinventory-agent systemd-ui openvpn network-manager-openvpn-gnome psensor lm-sensors nitrogen gnome-tweak-tool

if ! [[ -f /root/.listo ]]; then
	echo 'INTEL_BATCH="1"' >> /etc/environment
	echo "tmpfs /tmp tmpfs noexec,async,nosuid,noatime,nodev 0 0" >> /etc/fstab
	echo "tmpfs /var/cache/samba tmpfs noatime,async,nodev 0 0" >> /etc/fstab
	echo "tmpfs /var/log tmpfs noatime,async,nodev 0 0" >> /etc/fstab
	echo "tmpfs /var/spool tmpfs noatime,async,nodev 0 0" >> /etc/fstab
	echo "tmpfs /var/tmp tmpfs noexec,async,nosuid,noatime,nodev 0 0" >> /etc/fstab
	echo "tmpfs /home/$quien/.cache tmpfs noatime,noexec,nosuid,async,nodev,rw 0 0" >> /etc/fstab
	echo "proc /proc proc defaults,hidepid=2 0 0" >> /etc/fstab
	echo "tmpfs /run tmpfs rw,nosuid,async,noexec,nodev,noatime,mode=755 0 0" >> /etc/fstab
	echo "tmpfs /dev/shm tmpfs defaults,nodev,nosuid,noexec 0 0" >> /etc/fstab
	echo "# /etc/security/limits.conf" > /etc/security/limits.conf
	echo "* hard nproc 1000" >> /etc/security/limits.conf
	echo "* soft nofile 2000" >> /etc/security/limits.conf
	echo "* hard nofile 2000" >> /etc/security/limits.conf
	echo "# End of file" >> /etc/security/limits.conf
	echo "net.ipv6.conf.all.disable_ipv6 = 1" > "$ipv6"
	echo "net.ipv6.conf.default.disable_ipv6 = 1" >> "$ipv6"
	echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> "$ipv6"
	echo "kernel/mm/transparent_hugepage/enabled = always" >> "$sysf"
	echo "kernel/mm/transparent_hugepage/khugepaged/pages_to_scan = 20000" >> "$sysf"
	echo "kernel/mm/ksm/run = 1" >> "$sysf"
	echo "kernel/mm/ksm/pages_to_scan = 20000" >> "$sysf"
	echo "kernel/mm/ksm/sleep_millisecs = 200" >> "$sysf"
	echo "fs/cgroup/cpu/notify_on_release = 1" >> "$sysf"
	echo "fs/cgroup/cpu/release_agent = /usr/local/sbin/cgroup_clean" >> "$sysf"
	echo "fs/cgroup/cpu/notify_on_release = 1" >> "$sysf"
	echo "#!/bin/sh" > /usr/local/sbin/cgroup_clean
	echo "rmdir /sys/fs/cgroup/cpu/$*" >> /usr/local/sbin/cgroup_clean
	chmod +x /usr/local/sbin/cgroup_clean
	sed -i 's/127.0.0.1	localhost/127.0.0.1	localhost "$(hostname)"/g' /etc/hosts
	sed -i 's_/bin/bash_/usr/bin/fish_g' /etc/passwd
	sed -i 's/PRELINKING=unknown/PRELINKING=yes/g' /etc/default/prelink
	sed -i 's/PRELINK_OPTS=-mR/PRELINK_OPTS=-amR/g' /etc/default/prelink
	sed --in-place 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop
	echo -e "\nHidden=true\n"|tee --append /etc/xdg/autostart/tracker-extract.desktop
	echo -e "\nHidden=true\n"|tee --append /etc/xdg/autostart/tracker-miner-apps.desktop
	echo -e "\nHidden=true\n"|tee --append /etc/xdg/autostart/tracker-miner-fs.desktop
	echo -e "\nHidden=true\n"|tee --append /etc/xdg/autostart/tracker-miner-user-guides.desktop
	echo -e "\nHidden=true\n"|tee --append /etc/xdg/autostart/tracker-store.desktop
	gsettings set org.freedesktop.Tracker.Miner.Files crawling-interval -2
	gsettings set org.freedesktop.Tracker.Miner.Files enable-monitors false
	tracker reset --hard
	source /usr/share/doc/libdvdread4/install-css.sh
	yes "" | sensors-detect

	wget -q -O /tmp/vboxinstall - https://raw.githubusercontent.com/sinfallas/vm-install/master/virtualbox-install
	chmod +x /tmp/vboxinstall
	source /tmp/vboxinstall
	rm -f /tmp/vboxinstall

	wget -q -O /tmp/securegnupg - https://raw.githubusercontent.com/sinfallas/securegnupg/master/securegnupg
	chmod +x /tmp/securegnupg
	source /tmp/securegnupg
	rm -f /tmp/securegnupg

	wget -q -O /tmp/calc-mem - https://raw.githubusercontent.com/sinfallas/calc-mem/master/calc-mem
	chmod +x /tmp/calc-mem
	source /tmp/calc-mem
	rm -f /tmp/calc-mem
	
	wget -q -O /usr/bin/actualizar - https://raw.githubusercontent.com/sinfallas/misc/master/actualizar
	chmod +x /usr/bin/actualizar
	source /usr/bin/actualizar
	git config --global http.sslverify false
	touch /root/.listo
fi

echo -e "\e[00;1;92mFinalizado...\e[00m"
rm -f /run/$(basename $0).pid
exit 0
