#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C

if [[ "$EUID" != "0" ]]; then
        echo -e "\e[00;31mERROR: Debe ser root.\e[00m"
        exit 1
fi

mysql -uroot -ppassword -e "TRUNCATE mysql.general_log;"
mysql -uroot -ppassword -e "TRUNCATE mysql.slow_log;"

exit 0
