#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2

if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
	exit 1
fi

source /usr/bin/kzombie
sync; echo 3  > /proc/sys/vm/drop_caches
swapoff -a
swapon -a
source /etc/init.d/mizram start

exit 0
