#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2

if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
	exit 1
fi

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

apt update -qq
apt -y install docker-ce docker-ce-cli containerd.io

groupadd docker
usermod -aG docker $(who | cut -d' ' -f1 | sort | uniq)
newgrp docker
systemctl disable docker

#portainer.io
docker volume create portainer_data
docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
docker run -d -p 9001:9001 --name portainer_agent --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes portainer/agent

exit 0
