pref("extensions.update.enabled", true);
pref("intl.locale.matchOS", true);
pref("browser.shell.checkDefaultBrowser", false);
pref("gfx.font_rendering.opentype_svg.enabled", true);
pref("gfx.font_rendering.directwrite.enabled", true);
pref("network.dns.disablePrefetchFromHTTPS", false);
pref("privacy.trackingprotection.enabled", true);
pref("geo.enabled", false);
pref("network.proxy.socks_remote_dns", false);
pref("datareporting.healthreport.service.firstRun", false);
pref("datareporting.healthreport.service.enabled", false);
pref("datareporting.healthreport.uploadEnabled", false);
pref("datareporting.policy.dataSubmissionEnabled", false);
pref("toolkit.telemetry.enabled", false);
pref("toolkit.telemetry.prompted",2);
pref("browser.pocket.enabled", false);
pref("browser.pocket.api", "");
pref("browser.pocket.site", "");
pref("browser.pocket.useLocaleList", false);
pref("browser.search.suggest.enabled", false);
pref("browser.sessionstore.interval", 20000);
pref("media.peerconnection.enabled", false);
pref("privacy.donottrackheader.enabled", true);
pref("security.ssl3.dhe_rsa_aes_128_sha",false);
pref("security.ssl3.dhe_rsa_aes_256_sha",false);
pref("privacy.cpd.offlineApps", true);
pref("privacy.cpd.passwords", true);
pref("privacy.cpd.siteSettings", true);
pref("privacy.clearOnShutdown.sessions", true);
pref("privacy.clearOnShutdown.history", true);
pref("privacy.clearOnShutdown.formdata", true);
pref("privacy.clearOnShutdown.cookies",true);
pref("privacy.clearOnShutdown.downloads",true);
pref("privacy.clearOnShutdown.cache",true);
pref("privacy.sanitize.sanitizeOnShutdown",true);
pref("network.http.referer.trimmingPolicy", 1);
pref("network.http.referer.XOriginPolicy", 1);
pref("network.http.sendRefererHeader", 1);
pref("geo.wifi.uri", "");
pref("devtools.remote.wifi.scan", false);
pref("device.sensors.enabled", false);
pref("network.http.pipelining.ssl",true);
pref("network.http.proxy.pipelining",true);
pref("privacy.donottrackheader.value", 1);
