pref("extensions.update.enabled", true);
pref("intl.locale.matchOS", true);
pref("browser.shell.checkDefaultBrowser", false);
pref("gfx.font_rendering.opentype_svg.enabled", true);
pref("gfx.font_rendering.directwrite.enabled", true);
pref("network.dns.disablePrefetchFromHTTPS", false);
pref("privacy.trackingprotection.enabled", true);
pref("geo.enabled", false);
pref("network.proxy.socks_remote_dns", false);
pref("datareporting.healthreport.service.firstRun", false);
pref("datareporting.healthreport.service.enabled", false);
pref("datareporting.healthreport.uploadEnabled", false);
pref("datareporting.policy.dataSubmissionEnabled", false);
pref("browser.pocket.enabled", false);
pref("browser.pocket.api", "");
pref("browser.pocket.site", "");
pref("browser.pocket.useLocaleList", false);
pref("browser.search.suggest.enabled", false);
pref("browser.sessionstore.interval", 20000);
pref("media.peerconnection.enabled", false);
pref("privacy.donottrackheader.enabled", true);
pref("security.ssl3.dhe_rsa_aes_128_sha",false);
pref("security.ssl3.dhe_rsa_aes_256_sha",false);
pref("privacy.cpd.offlineApps", true);
pref("privacy.cpd.passwords", true);
pref("privacy.cpd.siteSettings", true);
pref("privacy.clearOnShutdown.sessions", true);
pref("privacy.clearOnShutdown.history", true);
pref("privacy.clearOnShutdown.formdata", true);
pref("privacy.clearOnShutdown.cookies",true);
pref("privacy.clearOnShutdown.downloads",true);
pref("privacy.clearOnShutdown.cache",true);
pref("privacy.sanitize.sanitizeOnShutdown",true);
pref("geo.wifi.uri", "");
pref("devtools.remote.wifi.scan", false);
pref("device.sensors.enabled", false);
pref("network.http.pipelining.ssl",true);
pref("network.http.proxy.pipelining",true);
pref("privacy.donottrackheader.value", 1);
pref("media.ffmpeg.vaapi-drm-display.enabled",true);
pref("media.ffmpeg.vaapi.enabled",true);
pref("gfx.webrender.all",true);
pref("browser.cache.disk.enable",false);
pref("browser.cache.memory.enable",true);
pref("browser.cache.memory.capacity",-1);
pref("network.security.esni.enabled",true);
pref("network.trr.mode",2);
pref("dom.max_script_run_time",20);
pref("browser.download.animateNotifications",false);
pref("security.dialog_enable_delay",0);
pref("toolkit.telemetry.enabled", false);
pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
pref("browser.newtabpage.activity-stream.telemetry", false);
pref("browser.ping-centre.telemetry", false);
pref("toolkit.telemetry.bhrPing.enabled", false);
pref("toolkit.telemetry.firstShutdownPing.enabled", false);
pref("toolkit.telemetry.hybridContent.enabled", false);
pref("toolkit.telemetry.newProfilePing.enabled", false);
pref("toolkit.telemetry.reportingpolicy.firstRun", false);
pref("toolkit.telemetry.shutdownPingSender.enabled", false);
pref("toolkit.telemetry.unified", false);
pref("toolkit.telemetry.updatePing.enabled", false);
pref("toolkit.telemetry.prompted",2);
pref("toolkit.telemetry.archive.enabled", false);
pref("network.prefetch-next", false);
pref("reader.parse-on-load.enabled", false);
pref("reader.parse-on-load.force-enabled", false);
pref("loop.enabled", false);
pref("dom.event.clipboardevents.enabled", false);
pref("dom.battery.enabled", false);
pref("privacy.firstparty.isolate",true);
pref("privacy.resistFingerprinting",true);
pref("network.http.http3.enabled",true);
