#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2

if [[ "$EUID" != "0" ]]; then
	echo "ERROR: debe ser root"
	exit 1
fi

mkdir -p /etc/sysctl.d
name="/etc/sysctl.d/10-calc-mem.conf"
memor=$(grep MemTotal /proc/meminfo | awk '{print $2}')
mb=$(( $memor * 1024 ))
mf=$(( $mb / 1024 * 0,01 ))
fm=$(( $mb / 4194304 * 256 ))
mo=$(( $mb * 0,10 / 65536 ))
mt=$(( $fm * 2 ))
page_size=$(getconf PAGE_SIZE)
phys_pages=$(getconf _PHYS_PAGES)
shmall=$(( $phys_pages / 2 ))
shmmax=$(( $shmall * $page_size ))
echo "kernel.shmmax = $shmmax" > "$name"
echo "kernel.shmall = $shmall" >> "$name"
echo "vm.min_free_kbytes = $mf" >> "$name"
echo "fs.file-max = $fm" >> "$name"
echo "net.ipv4.tcp_max_orphans = $mo" >> "$name"
echo "net.ipv4.tcp_max_tw_buckets = $mt" >> "$name"
if (( $memor < 1024000 )); then
        echo "vm.dirty_ratio = 25" >> "$name"
        echo "vm.dirty_background_ratio = 15" >> "$name"
        echo "vm.dirty_expire_centisecs = 750" >> "$name"
        echo "vm.dirty_writeback_centisecs = 125" >> "$name"
else
        if (( $memor > 4096000 )); then
            echo "vm.swappiness = 10" >> "$name"
            echo "vm.vfs_cache_pressure = 50" >> "$name"
        fi
        if (( $memor < 8192000 )); then
            echo "vm.dirty_ratio = 12" >> "$name"
            echo "vm.dirty_background_ratio = 10" >> "$name"
            echo "vm.dirty_expire_centisecs = 1500" >> "$name"
            echo "vm.dirty_writeback_centisecs = 250" >> "$name"
        else
            echo "vm.dirty_ratio = 3" >> "$name"
            echo "vm.dirty_background_ratio = 5" >> "$name"
            echo "vm.dirty_expire_centisecs = 3000" >> "$name"
            echo "vm.dirty_writeback_centisecs = 500" >> "$name"
        fi
fi
sysctl -p

apt -q update
apt -y install libcurl3 curl sudo htop oitop iftop powertop samba
mv -fv /etc/samba/smb.conf /etc/samba/smb.conf.old

cat <<EOF >>/etc/samba/smb.conf
[global]
        pam password change = yes
        dns proxy = no
        panic action = /usr/share/samba/panic-action %d
        map to guest = bad user
        passwd program = /usr/bin/passwd %u
        workgroup = WORKGROUP
        passdb backend = tdbsam
        log file = /var/log/samba/log.%m
        max log size = 1000
        server string = %h server (Samba, Ubuntu)
        netbios name = ubuntusql
        netbios aliases = ubuntusql
        unix password sync = yes
        passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
        default = logshipping
        usershare allow guests = yes
        os level = 20
        server role = standalone server
        obey pam restrictions = yes

[printers]
   comment = All Printers
   browseable = no
   path = /var/spool/samba
   printable = yes
   guest ok = no
   read only = yes
   create mask = 0700

[print$]
   comment = Printer Drivers
   path = /var/lib/samba/printers
   browseable = yes
   read only = yes
   guest ok = no

[logshipping]
        path = /var/opt/mssql/data/casa
        delete readonly = yes
        wide links = no
        valid users = sqlserver,mssql
        write list = mssql
        force user = root
        public = yes
        writeable = yes
EOF
systemctl restart smbd

wget -qO- https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)"
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/msprod.list
apt -q update
apt -y install mssql-server
/opt/mssql/bin/mssql-conf setup
ACCEPT_EULA=Y apt -y install mssql-tools unixodbc-dev
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
systemctl stop mssql-server
systemctl edit mssql-server 
#[Service]
#Environment="LD_LIBRARY_PATH=/opt/mssql/lib" 
ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 /opt/mssql/lib/libssl.so 
ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /opt/mssql/lib/libcrypto.so 
systemctl start mssql-server
/opt/mssql/bin/mssql-conf set sqlagent.enabled true
systemctl restart mssql-server
mkdir -p /var/opt/mssql/data/back

exit 0
