#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2

if [[ "$EUID" = "0" ]]; then
	echo "ERROR: No debe ser root."
	exit 1
fi
gsettings set org.freedesktop.Tracker.Miner.Files crawling-interval -2
gsettings set org.freedesktop.Tracker.Miner.Files enable-monitors false
gsettings set org.freedesktop.Tracker.Miner.Files index-on-battery false
gsettings set org.freedesktop.Tracker.Miner.Files index-on-battery-first-time false
gsettings set org.gnome.desktop.background show-desktop-icons false
gsettings set org.gnome.desktop.search-providers disable-external true
gsettings set org.gnome.desktop.sound event-sounds false
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.interface enable-hot-corners true
gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.media-handling autorun-never true
gsettings set org.gnome.desktop.privacy remember-app-usage false
gsettings set org.gnome.desktop.privacy remember-recent-files false
gsettings set org.gnome.desktop.privacy old-files-age "7"
gsettings set org.gnome.desktop.privacy remove-old-temp-files true
gsettings set org.gnome.desktop.privacy remove-old-trash-files true
gsettings set org.gnome.desktop.privacy report-technical-problems false
gsettings set org.gnome.desktop.privacy send-software-usage-stats false
gsettings set org.gnome.desktop.privacy hide-identity true
gsettings set org.gnome.desktop.privacy recent-files-max-age "0"
gsettings set org.gnome.desktop.wm.preferences disable-workarounds true
gsettings set org.gnome.desktop.thumbnailers disable-all true
gsettings set org.gnome.desktop.peripherals.touchpad disable-while-typing true
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.peripherals.touchpad two-finger-scrolling-enabled true
gsettings set org.gnome.desktop.peripherals.mouse middle-click-emulation true
gsettings set org.gnome.desktop.notifications show-in-lock-screen false
gsettings set org.gnome.desktop.interface clock-format '12h'
gsettings set org.gnome.nautilus.preferences confirm-trash false
gsettings set org.gnome.nautilus.preferences show-delete-permanently true
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode 'FIXED'
gsettings set org.gnome.shell.extensions.dash-to-dock background-opacity 0.1
gsettings set org.gnome.system.location enabled false
gsettings set org.gnome.SessionManager logout-prompt true
gsettings set org.gnome.settings-daemon.plugins.power idle-dim true
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.settings-daemon.plugins.a11y-keyboard active false
gsettings set org.gnome.settings-daemon.plugins.a11y-settings active false
gsettings set org.gnome.settings-daemon.plugins.gsdwacom active false
gsettings set org.gnome.settings-daemon.plugins.smartcard active false
gsettings set org.gnome.Terminal.Legacy.Settings confirm-close false
gsettings set com.ubuntu.touch.network gps false
gsettings set org.gnome.software download-updates false
gsettings set org.gnome.software allow-updates false
gsettings set org.gnome.gnome-flashback screencast false
dconf write /apps/seahorse/server-auto-publish true
dconf write /apps/seahorse/server-auto-retrieve true
dconf write /org/gnome/desktop/remote-access/require-encryption false
dconf write /org/gnome/desktop/remote-access/lock-screen-on-disconnect true
dconf write /org/gnome/desktop/remote-access/disable-background true
dconf write /org/gnome/desktop/notifications/application/update-manager/enable false
dconf write /org/gtk/settings/file-chooser/clock-format "'12h'"
dconf write /org/freedesktop/tracker/miner/files/index-recursive-directories "['']"
dconf write /org/freedesktop/tracker/miner/files/index-on-battery-first-time false
dconf write /org/freedesktop/tracker/miner/files/index-on-battery false
exit 0
