#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
source /usr/bin/mivariable
siroot
clear

if [[ -z $1 ]]; then
	echo "ERROR: Debe indicar la version a descargar"
	exit 1
fi

rm -f /usr/bin/RuneLite.AppImage
echo "Descargado RuneLite.AppImage"
wget -O /tmp/RuneLite.AppImage https://github.com/runelite/launcher/releases/download/$1/RuneLite.AppImage
mv -f /tmp/RuneLite.AppImage /usr/bin/
chmod 777 /usr/bin/RuneLite.AppImage
clear

echo "Descargado runelite.png"
wget -O /tmp/runelite.png https://raw.githubusercontent.com/runelite/launcher/master/appimage/runelite.png
mv -f /tmp/runelite.png /usr/share/icons/runelite.png
chmod 644 /usr/share/icons/runelite.png

printf '[Desktop Entry]\nEncoding=UTF-8\nType=Application\nIcon=/usr/share/icons/runelite.png\nExec=/usr/bin/RuneLite.AppImage\nName=RuneLite\nTerminal=false\nComment=An opensource third party client for Old School RuneScape\nCategories=Games;' > /usr/share/applications/runelite.desktop
chmod 644 /usr/share/applications/runelite.desktop
clear
echo "Finalizado."
exit 0
