#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
coman="adb shell pm uninstall --user 0"

if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
	exit 1
fi

case "$1" in
	basico)
		$coman com.android.bookmarkprovider
		$coman com.android.browser
		$coman com.mipay.wallet.id
		$coman com.mipay.wallet.in
		$coman com.micredit.in
		$coman com.miui.analytics
		$coman com.miui.hybrid
		$coman com.miui.hybrid.accessory
		$coman com.miui.msa.global
		$coman com.miui.nextpay
		$coman com.miui.yellowpage
		$coman com.miui.videoplayer
		$coman com.miui.notes
		$coman com.miui.systemAdSolution
		$coman com.xiaomi.glgm
		$coman com.xiaomi.joyose
		$coman com.xiaomi.payment
		$coman com.xiaomi.news
		$coman com.xiaomi.shop
		$coman com.android.calendar
		$coman com.mi.globalbrowser
		$coman com.facebook.services
		$coman com.facebook.system
		$coman com.facebook.appmanager
		$coman com.tencent.soter.soterserver
		$coman com.tencent.soter.soterservice
		$coman com.google.android.videos
		$coman com.google.android.music
		$coman com.google.android.apps.books
		$coman com.mi.global.bbs
		$coman com.mi.global.shop
		$coman com.mi.globalTrendNews
		;;
		
	app)
		$coman $2	
		;;	

	*)
		echo "uso: $(basename $0) {basico|app <nombre>}"
		;;

esac
exit 0
